name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  container-name:
    description: 'Docker container name to use'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    run: |
      set -euxo pipefail
      CONTAINER_NAME=${{ inputs.container-name }}
      TAG=runtimeverificationinc/${CONTAINER_NAME}
      K_VERSION=$(cat deps/k_release)
      docker build .                                  \
        --file .github/actions/with-docker/Dockerfile \
        --tag ${TAG}                                  \
        --build-arg K_VERSION=${K_VERSION}
      docker run                          \
        --name ${CONTAINER_NAME}          \
        --rm                              \
        --interactive                     \
        --tty                             \
        --detach                          \
        --user root                       \
        --workdir /home/user              \
        ${TAG}
      docker cp . ${CONTAINER_NAME}:/home/user
      docker exec ${CONTAINER_NAME} chown -R user:user /home/user
